### ISSUE TITLE
Env and Social Obligations shouldn't be one_to_many

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#76]
A company can only have one set of Env and Social Obligations.

(remove 'Create Another Env and social obligation' button)

**Comment by markmcdonald51** [comment]
done

**Comment by jameslaneconkling** [comment]
@markmcdonald51 Unless this hasn't been deployed yet, I'm still seeing the option to *create another Env and social obligation*.  These fields only need to be defined once for each company.

**Comment by markmcdonald51** [comment]
check again James. I think what you're seeing is 'Replace With New' which just clears out those fields and let's you re-add in new ones. Like a reset button.
