### ISSUE TITLE
Social Projects

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#77]
Add year field.

Reorder the fields in the input form according to the order in the [spreadsheet documentation](https://docs.google.com/spreadsheets/d/1FhdHEGWVYgImtm10Hj5B35F2WvQs5GyZWaD52zrClgk/edit#gid=1613944963).

**Comment by markmcdonald51** [comment]
done

**Comment by jameslaneconkling** [comment]
@markmcdonald51 Unless they haven't been deployed yet, still not seeing the necessary changes:
* needs year
* should not have a *company* field.  (company is of course the company whose being edited)
* should not have option to 'Add Existing'

As for reordering the fields, I've assigned this to @charleshuang80 on the *site translation* ticket #70 .  @markmcdonald51 can you make sure he knows both how to translate the labels, and reorder the fields (CC have been giving me a lot of flack about the ordering of fields).

**Comment by markmcdonald51** [comment]
Hi James,
I am going to add in a year field but from your doc I dont see this field as a requirement, thus it wasn't added.

see: https://docs.google.com/spreadsheets/d/1FhdHEGWVYgImtm10Hj5B35F2WvQs5GyZWaD52zrClgk/edit#gid=1613944963
added migration to add year to social projects table
removed  option to 'Add Existing'
